---
title: "labpca"
format: html
editor: visual
---

```{r}
library(tidyverse)
```

```{r}
download.file(
  url = "https://raw.githubusercontent.com/rdpstaff/AlignmentTools/master/src/data/blosum62.txt",
  destfile = "data/blosum62.txt")
bl62 <- read_table(
  file = "data/blosum62.txt",
  comment = "#")
bl62
```

```{r}
colnames(bl62) <- c("aa", colnames(bl62))
std_aa = c("A", "R", "N", "D", "C", "Q", "E", "G", "H", "I",
           "L", "K", "M", "F", "P", "S", "T", "W", "Y", "V")
bl62 <- bl62 |> 
  filter(aa %in% std_aa) |> 
  select(aa, std_aa)
bl62
```

```{r}
pl <- bl62 |>
  pivot_longer(
    cols = -aa,
    names_to = "aa2",
    values_to = "log_odds_score") |> 
  ggplot(aes(
    x = factor(aa,
               levels = std_aa),
    y = factor(aa2,
               levels = rev(std_aa)),
    fill = log_odds_score,
    label = log_odds_score)) +
  geom_tile() +
  geom_text(colour = "darkgrey",
            size = 7) +
  scale_fill_gradient2(low = "blue",
                       mid = "white",
                       high = "red",
                       midpoint = 0) +
  scale_x_discrete(position = "top") +
  coord_fixed() +
  theme_minimal(base_size = 22,
                base_family = "Avenir") +
  theme(legend.position = "none",
        plot.title = element_text(
          hjust = 0.5,
          vjust = -4)) +
  labs(
    x = "",
    y = "",
    title = str_c(
    "The BLOSUM62 Visualised ",
    "as a Heatmap"))
```

```{r}
bl62_pca <- bl62 |>
  select_if(is.numeric) |>
  prcomp(center = TRUE,
         scale = TRUE)
bl62_pca |>
  str()
```

```{r}
bl62_pca |>
  tidy("pcs")
```

```{r}
bl62_pca |>
  tidy("pcs") |> 
  mutate(percent = percent * 100) |> 
  ggplot(aes(x = PC,
             y = percent)) +
  geom_hline(yintercept = 0) +
  geom_col(colour = "black",
           alpha = 0.5) +
  theme_bw(base_size = 20) +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank()) +
  labs(title = "Scree Plot of PCA of BLOSUM62")
```

```{r}
bl62_pca_aug <- bl62_pca |>
  augment(bl62)
bl62_pca_aug
```

```{r}
get_chem_class <- function(x){
  chem_cols <- c(
    "A" = "Hydrophobic",
    "R" = "Basic",
    "N" = "Neutral",
    "D" = "Acidic",
    "C" = "Sulphur",
    "Q" = "Neutral",
    "E" = "Acidic",
    "G" = "Polar",
    "H" = "Basic",
    "I" = "Hydrophobic",
    "L" = "Hydrophobic",
    "K" = "Basic",
    "M" = "Sulphur",
    "F" = "Hydrophobic",
    "P" = "Hydrophobic",
    "S" = "Polar",
    "T" = "Polar",
    "W" = "Hydrophobic",
    "Y" = "Polar",
    "V" = "Hydrophobic")
  return( chem_cols[x] ) # Example of avoiding dependencies => shareable!
}
```

```{r}
get_chem_class(x = c("A", "R", "D"))
bl62_pca_aug <- bl62_pca_aug |> 
  mutate(chem_class = get_chem_class(aa))

bl62_pca_aug |>
  select(aa, chem_class)
```

```{r}
pca_plot_axes_labels <- bl62_pca |>
  tidy("eigenvalues") |>
  mutate(lbl = str_c("PC", PC, ", VE = ", round(percent*100,2), "%")) |> 
  pull("lbl")
pca_plot_axes_labels
```

```{r}
pca_plot <- bl62_pca_aug |> 
  ggplot(aes(x = .fittedPC1,
             y = .fittedPC2,
             label = aa,
             colour = chem_class,
             fill = chem_class)) +
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0) +
  geom_point(shape = 21,
             size = 6,
             alpha = 0.5) +
  geom_text(colour = "black") +
  scale_fill_manual(
    values = c("red", "blue", "black",
               "purple", "green", "yellow")) +
  scale_colour_manual(
    values = c("red", "blue", "black",
               "purple", "green", "yellow")) +
  coord_fixed() +
  theme_bw(base_size = 20,
           base_family = "avenir") +
  labs(
    title = "PCA: Scores Plot of BLOSUM62",
    x = pluck(pca_plot_axes_labels, 1),
    y = pluck(pca_plot_axes_labels, 2),
    fill = "Chemistry",
    colour = "Chemistry",
    caption = "Up: Aromatic, down: Aliphatic, Left: Charged, Right: Hydrophobic")

pca_plot 
```

```{r}

```
